apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
