{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service.fullname" . }}
  labels:
{{ include  "service.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{ include  "service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.servicemonitor.interval }}
      path: {{ .Values.servicemonitor.path }}
{{- end }}