nameOverride: "accommodation-service"
fullnameOverride: "accommodation-service"

namespace: "helm-booking"


deployment:
  image: "katarinakomad/accommodation-service"
  tag: "0.14.0"
  replicaCount: 1
  containerPort: 8002
  probes:
    initialDelaySeconds: 3
    livenessPath: /q/health/live
    readinessPath: /q/health/ready

service:
  type: ClusterIP
  port: 8002

configmap:
  data:
    INIT_DATA_SCRIPT: "no-file"
    INIT_DATA_BOOL: "false"
    CREATE_DB_OPTION: "none"
    POSTGRESQL_DB: "accommodationDB"
    USER_SERVICE_API: "http://user-service:8001/api/user-service"
    RESERVATION_SERVICE_API: "http://reservation-service:8003/api/reservation-service"
    NOTIFICATION_SERVICE_API: "http://notification-service:8004/api/notification-service"
    JAEGER_ENDPOINT: "http://jaeger-collector.monitoring:14268/api/traces"

servicemonitor:
  enabled: true # enabled by default
  interval: 15s
  path: /metrics

alerts:
  enabled: false

secret: {}
