nameOverride: "accommodation-service"
fullnameOverride: "accommodation-service"

namespace: "helm-booking"


deployment:
  image: "katarinakomad/accommodation-service"
  tag: "latest"
  replicaCount: 1
  containerPort: 8002
  probes:
    initialDelaySeconds: 3
    livenessPath: /probe/liveness
    readinessPath: /probe/readiness

service:
  type: ClusterIP
  port: 8002

configmap:
  data:
    INIT_DATA_SCRIPT: "import.sql"
    INIT_DATA_BOOL: "true"
    CREATE_DB_OPTION: "drop-and-create"
    POSTGRESQL_DB: "accommodationDB"
    USER_SERVICE_API: "http://user-service:8001/api/user-service"
    RESERVATION_SERVICE_API: "http://reservation-service:8003/api/reservation-service"

secret: {}
