nameOverride: "notification-service"
fullnameOverride: "notification-service"

namespace: "helm-booking"


deployment:
  image: "katarinakomad/notification-service"
  tag: "0.14.1"
  replicaCount: 1
  containerPort: 8004
  probes:
    initialDelaySeconds: 3
    livenessPath: /q/health/live
    readinessPath: /q/health/ready

service:
  type: ClusterIP
  port: 8004

configmap:
  data:
    USER_SERVICE_API: "http://user-service:8001/api/user-service"
    ACCOMMODATION_SERVICE_API: "http://accommodation-service:8002/api/accommodation-service"
    RESERVATION_SERVICE_API: "http://reservation-service:8003/api/reservation-service"
    JAEGER_ENDPOINT: "http://jaeger-collector.monitoring:14268/api/traces"

servicemonitor:
  enabled: true # enabled by default
  interval: 15s
  path: /metrics

alerts:
  enabled: false

secret: {}
