name: user-service

nameOverride: "user-service"
fullnameOverride: "user-service"

namespace: "helm-booking"


deployment:
  image: "katarinakomad/user-service"
  tag: "latest"
  replicaCount: 1
  containerPort: 8001
  probes:
    initialDelaySeconds: 3
    livenessPath: /probe/liveness
    readinessPath: /probe/readiness

service:
  type: ClusterIP
  port: 8001

configmap:
  data:
    INIT_DATA_SCRIPT: "no-file"
    INIT_DATA_BOOL: "false"
    CREATE_DB_OPTION: "none"
    POSTGRESQL_DB: "userDB"
    ACCOMMODATION_SERVICE_API: "http://accommodation-service:8002/api/accommodation-service"
    RESERVATION_SERVICE_API: "http://reservation-service:8003/api/reservation-service"


secret: {}