version: '3.8'

services:
  dependencies:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"