apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    # path: <local-directory> # replace with local directory, such as "/home/<user-name>/kaniko"
    path: "/mnt/d/Faks/1.master/2.semestar/DevOps/Projekat/config/kube-kaniko"  