apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.configmap.data) $ | nindent 2 }}

